### ISSUE TITLE
duplicate id

### ISSUE THREAD

**Issue by redon** [wout/svg.import.js#30]
Today I changed to svg.import.js 1.0.1
now I get an error

Encountered duplicate id "sy". Changed store key to "sy8655266274004099".

There are no duplicated ids in that single element, but I am importing multiple svg and they all all have an id "sy"

Should I change something?

Thank You

**Comment by JonathanBesson** [comment]
+1. If someone find this issue, notice here please. Thank you a lot.

**Comment by ctzurcanu** [comment]
+1

**Comment by kylophone** [comment]
I think I figured this out. It looks like the bug is in the minified code only. When I use the unminified code, this behavior goes away. Should be a simple fix, if I have a second I'll submit a pull request. 

```js
<script src="./svg.import.min.js"></script> // tons of 'duplicate id' errors.
<script src="./svg.import.js"></script> // works great.
```

**Comment by kylophone** [comment]
Cool, this pull fixes this issue: https://github.com/wout/svg.import.js/pull/40

**Comment by redon** [comment]
Yes, that helped!
Thank you!
