### ISSUE TITLE
Throws a TypeError: SVG.defaults.trans is not a function

### ISSUE THREAD

**Issue by PrashntS** [wout/svg.import.js#44]
While importing any SVG, it's been throwing the above mentioned TypeError. The origin is line number 27.
I fixed it by changing line 27
from:
```javascript
        , def   = SVG.defaults.trans()
```
to: 
```javascript
        , def   = SVG.defaults
```

What is the purpose of this line, and why is the `trans()` method removed? Is my fix correct, or does it breaks something too?

**Comment by dhardtke** [comment]
This is really weird.

Have a look at this:
https://jsfiddle.net/w5zod1m3/1/
(parser and import plugin embedded as inline script and *it works*)

versus
https://jsfiddle.net/w5zod1m3/2/
(parser and import plugin embedded as external resources and it *does not work*)

I'll investigate this further...

**Comment by Smileo** [comment]
Hi there, any news?

**Comment by Smileo** [comment]
I see that on http://svgjs.com/import/ same error.

**Comment by PrashntS** [comment]
Yes.
Same goes for [clock example](http://svgjs.com/clock/) - doesn't work.

**Comment by Fuzzyma** [comment]
This plugin is NOT for svg.js v2 because in v2 you can do that with the lib alone

**Comment by Smileo** [comment]
Thanks @Fuzzyma you are right, It's work for me )
